language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Bzxt+2iiB1rBbRfgKFqpCSjMsddHEM/HhVxdKnsrub1Wc2BP0TU4Q2XT91fckIzJzOsQm5smXGlNB0pnMe7+7IOh8WJ99EhWtowuPWKBkgA7ZpBO/SiGA7+zwFD4mW9j10JVi8XYUbVTGBGtoSprL1l9bzK0Buf6dZ29VMFCEp0lheMJpfKkBfLe9FwaesaUOoOVK25Nin1cslGlDRyBoLKSyqZ3qt2tPtBVA1vTUWmzhurXutlhcksf9IZhCkFrznjttiVrqUWJNDzxjIHzKaOMdvMmPb4v6D43qMAjM0E9RCpDBG8NPYH70yih73V04mpvw5mtLzOyn1IR1H+lLzieSdwPD8+8QU8DN2/PhASfMO5FU4Wr9oqSDN3jzONOSZusjoSR4YDGNRtQrFBtl5ZOwU5K6ad71H/hS9ivsakAuGjP2HGpFqSuqQI1skm1DeEF1X1ZN0vpcVtNh4ktzsOvToH0cUSHWxXf2T20rGzuk2R3oOh+C5bZmCpHuk1QFSj+QsbtFYfN3mu6G+3C8ePE+iRuhaS5Et9gzEMMOybiV1O2GdVzhdLTA6V1bsX3p1g6SwzRtcMNmRQ45GtDQFT4k9lUvc23OuoxccO2nz7DT+kh3gvzsQE+owuVczDcuAb+PWIsznCZAnetG0bGzZGkcQfkRETL23ScqCvz7GU=
  app: dry-savannah-46870
  on:
    repo: mike31415/node_capstone
